CREATE TABLE [dbo].[kekhai](
	[_id] [int] IDENTITY(1,1) NOT NULL,
	[sohoso] [nvarchar](255) NULL,
	[matochuc] [nvarchar](255) NULL,
	[tentochuc] [nvarchar](255) NULL,
	[madaily] [nvarchar](255) NULL,
	[tendaily] [nvarchar](255) NULL,
	[maloaihinh] [nvarchar](255) NULL,
	[tenloaihinh] [nvarchar](255) NULL,

	[masobhxh] [nvarchar](10) NULL,
	[hoten] [nvarchar](255) NULL,
	[ngaysinh] [date] NULL,
	[gioitinh] [bit] NULL,
	[cccd] [nvarchar](12) NULL,
	[dienthoai] [nvarchar](10) NULL,

	[maphuongan] [nvarchar](255) NULL,
	[tenphuongan] [nvarchar](255) NULL,
	[nguoithu] [int] NULL,
	[tienluongcs] [float] NULL,
	[sotien] [float] NULL,

	[tylengansachdiaphuong] [int] NULL,
	[hotrokhac] [int] NULL,
	[tungay] [date] NULL,
	[tyledong] [int] NULL,
	[muctiendong] [float] NULL,
	[maphuongthucdong] [nvarchar](255) NULL,
	[tenphuongthucdong] [nvarchar](255) NULL,

	[sothang] [int] NULL,
	[tuthang] [date] NULL,
	[tientunguyendong] [float] NULL,
	[tienlai] [float] NULL,
	[madoituong] [nvarchar](255) NULL,
	[tendoiduong] [nvarchar](255) NULL,
	[tylensnnht] [int] NULL,
	[tiennsnnht] [float] NULL,
	[tylensdp] [int] NULL,
	[tiennsdp] [float] NULL,

	[matinh] [nvarchar](255) NULL,
	[tentinh] [nvarchar](255) NULL,
	[maquanhuyen] [nvarchar](255) NULL,
	[tenquanhuyen] [nvarchar](255) NULL,
	[maxaphuong] [nvarchar](255) NULL,
	[tenxaphuong] [nvarchar](255) NULL,
	[tothon] [nvarchar](500) NULL,
	[benhvientinh] [nvarchar](255) NULL,
	[mabenhvien] [nvarchar](255) NULL,
	[tenbenhvien] [nvarchar](255) NULL,
	[ghichu] [nvarchar](max) NULL,
	
	[createdAt] [nvarchar](255) NULL,
	[createdBy] [nvarchar](255) NULL,
	[updatedAt] [nvarchar](255) NULL,
	[updatedBy] [nvarchar](255) NULL,

	[dotkekhai] [nvarchar](255) NULL,
	[kykekhai] [nvarchar](255) NULL,
	[ngaykekhai] [datetime] NULL,
	[trangthai] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
